frontend: 'https://example.com' # Required for CORS
nodeName: 'local-node'

deployment:
  labels: { 'yokanga.xyz/api': 'daphine' }
  replicaCount: 3
  image:
    repository: 'ghcr.io/jordojordo/daphine'
    pullPolicy: 'IfNotPresent'
    tag: ''

service:
  type: 'ClusterIP'
  port: 3000

storageClassName: 'local-storage'

pv:
  name: 'daphine-pv'
  type: 'local'
  storage: '20Gi'
  volumeMode: 'Filesystem'
  hostPath: '/mnt/assets'
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: 'kubernetes.io/hostname'
              operator: In
              values:
                - 'local-node'

pvc:
  name: 'daphine-pvc'
  storageRequest: '20Gi'
